- README.md
- onload/base/kustomization.yaml
- onload/cplane/cplane.yaml
- onload/dev/kustomization.yaml
- onload/deviceplugin/0000-buildconfig.yaml
- onload/deviceplugin/1000-deviceplugin.yaml
- onload/imagestream/imagestream.yaml
- onload/kmm/kustomization.yaml
- onload/kmm/module-nameref.yaml
- onload/kmm/onload-module.yaml
- onload/userbuild/buildconfig.yaml
A series of small patches to decouple the Onload OCP resources (module, UL, CP DS, device plugin) from their initial (individual) namespaces so that now it's managed by Kustomize, which puts all resources in a single configurable namespace.
My choice of a name was `onload-runtime` as the default namespace. (Another namespace is `onload-artifacts` for the images, which was introduced in one of the earlier PRs.)
Additionally, updated README and other small fixes.
---
Testing in OCP v4.12.
Created an image stream:
```console
$ oc apply -f onload/imagestream/imagestream.yaml
namespace/onload-artifacts created
rolebinding.rbac.authorization.k8s.io/system:image-puller created
imagestream.image.openshift.io/onload-user created
imagestream.image.openshift.io/onload-device-plugin created
``` …
> ON-14968: Support Kustomize "namespace" in Onload

- README.md
- onload/deviceplugin/0000-buildconfig.yaml
- onload/deviceplugin/Dockerfile
Add build triggers to the Onload device plugin.
We couldn't anonymously pull the device plugin sources from the internet until we published this repository. Instead, we (temporarily) asked the user to trigger the device plugin build locally/manually with `oc start-build ... --from-dir ...`. Now, we can pull the sources, so this patch instantiates the triggers.
Because the device plugin image is based on the Onload UL build image, the trigger specifically refers to the onload-user ImageStreamTag to retrigger the build as soon as the new Onload UL image is available.
When all Onload resources are created simultaneously, e.g. with Kustomize, the UL build may not be available, and it may cause the early device plugin builds to fail, but once UL is ready, the build restarts and succeeds.
--- …
> cleanup: Trigger device plugin build automatically

- examples/cns-sfnettest.yaml
- onload/deviceplugin/1000-deviceplugin.yaml
Set the `container_file_t` type for all files in `/opt/onload` in the compute nodes from the device plugin DS.
The device plugin DS copies Onload files from the UL build image into the node filesystem, ready for use in the user pods when they request the relevant resources with `resources.limits.amd.com/onload: 1`. However, SELinux refuses to grant access to these files to unprivileged pods because they have a wrong `type` in the SELinux `user:role:type:level`. The pods have the `container_file_t` type, but the Onload files have the `var_t` type.
To address the mismatch, the device plugin DS runs `chcon` to set the type in `/opt/onload` recursively.
Note that the `chcon` changes are not permanent and will be reset in the next autorelabel with SELinux. This patch operates on the assumption …
> ON-14920: Reduce example pods capabilities

- onload/cplane/cplane.yaml
- onload/deviceplugin/0000-buildconfig.yaml
- onload/deviceplugin/Dockerfile
- onload/kmm/Dockerfile
- onload/kmm/onload-module.yaml
- onload/userbuild/Dockerfile
- onload/userbuild/buildconfig.yaml
- sfc/kmm/sfc-module.yaml
We want to avoid using `latest` as a tag for our produced images.
Since running onload in a cluster is dependent on any new developments for onload, I think it should be fine to use a fixed tag to pull from github.
This doesn't touch `onload-device-plugin` or `sfnettest` images
Builds and runs in a 4.12.12 cluster
> ON-15010: Use a fixed tag for onload builds

- README.md
- onload/cplane/cplane.yaml
- onload/deviceplugin/0000-buildconfig.yaml
- onload/deviceplugin/1000-deviceplugin.yaml
- onload/deviceplugin/Dockerfile
- onload/imagestream/imagestream.yaml
- onload/kmm/onload-module.yaml
- onload/userbuild/buildconfig.yaml
We are contrasting against official Onload images, therefore renaming to onload-clusterlocal.
Suggested-by: Peter Colledge <peter.colledge@amd.com>
> cleanup: Rename onload-artifacts to onload-clusterlocal

- examples/sfnettest/cns-sfnettest.yaml
The "sfnettest" pod re-uses the default "ubi8/ubi-init" user, which is the root, and it conflicts with the pod restriction "runAsNonRoot". It causes the CreateContainerConfigError and prevents the pod from starting.
To address the error, this patch overrides the default user with 1001.
Reported-by: James Jay <jjay@xilinx.com>
---
Testing:
```
$ oc apply -k examples/profiles/latency/
```
Then (once the build it complete, in the default namespace):
```console
$ oc get pod
NAME                       READY   STATUS      RESTARTS   AGE
onload-sfnettest-1-build   0/1     Completed   0          11m
onload-sfnettest-client    1/1     Running     0          10s
onload-sfnettest-server    1/1     Running     0          10s
```
---
Why 1001? It seems like the recommended practice. I also peeked into …
> fix: Set default user 1001 for sfnettest image

- sfc/mco/sfc-pull-kernel-module-image.sh
- sfc/mco/sfc-replace-kernel-module.sh
Without this change the machineconfig scripts would try to pull a non-existant image
> ON-14971: Use correct sfc-module image tags in mc scripts

- README.md
Previous versions of `README.md` only properly documented how to install the sfc MachineConfig, now it has appropriate instructions for both KMM and MCO
> ON-14965: Document sfc OoT driver installation methods

- README.md
- sfc/kmm/Dockerfile
- sfc/kmm/kustomization.yaml
- sfc/kmm/module-nameref.yaml
- sfc/kmm/sfc-module.yaml
This allows us to separate out the `Dockerfile` for use with `podman` outside of a cluster.
Additionally, it should allow for multiple kustomizations eg for debug/release versions.
`sfc-module` builds and deploys in cluster.
> ON-15020: Use kustomize to deploy SFC KMM

- README.md
- base/kustomization.yaml
- base/onload-sources.conf
- onload/base/kustomization.yaml
- onload/build/deviceplugin/0000-buildconfig.yaml
- onload/build/deviceplugin/Dockerfile
- onload/build/userbuild/Dockerfile
- onload/build/userbuild/buildconfig.yaml
- onload/kmm/Dockerfile
- onload/kmm/onload-module.yaml
- sfc/kmm/Dockerfile
- sfc/kmm/kustomization.yaml
- sfc/kmm/sfc-module.yaml
Adds a cluster/ directory with an onload-sources.conf file which specificies the locations of tarballs for the Dockerfiles to pull and build from. This defaults to using github as the source, but this change will allow for easy configuration if github is inaccesible.
Also adds kustomization replacements to update the buildArgs for the onload and sfc builds. Existing command line invocations should be unaffected by this change.
Works in cluster, also tested with a local http server which provided the onload tarball
> ON-14945: Add kustomization to configure source locations

- README.md
- onload/build/diagnostics/ContainerFileNotice
- onload/build/diagnostics/Dockerfile
- onload/build/diagnostics/buildconfig.yaml
- onload/build/diagnostics/kustomization.yaml
- onload/build/kustomization.yaml
- onload/imagestream/imagestream.yaml
Package Onload troubleshooting utilities in the new "onload-debug" image. Containers based on that image must be privileged to access devfs files in the nodes needed for "onload_stackdump" and others to gather data.
> ON-15024: Add Onload diagnostics container

- base/onload-sources.conf
- examples/sfnettest/ContainerFileNotice
- examples/sfnettest/build/kustomization.yaml
- examples/sfnettest/build/sfnettest-build.yaml
- onload/build/deviceplugin/ContainerFileNotice
- onload/build/diagnostics/ContainerFileNotice
- onload/build/userbuild/ContainerFileNotice
- onload/cplane/ContainerFileNotice
- onload/kmm/ContainerFileNotice
- sfc/kmm/ContainerFileNotice
- sfptpd/build/kustomization.yaml
- sfptpd/build/sfptpd-build.yaml
Currently only `onload` and `kubernetes-onload` are included in `onload-sources.conf`, this change updates the file to include definitions for the locations of `sfptpd` and `sfnettest`.
End-to-end test in cluster. Everything builds and runs (including sfptpd)
> ON-14945: Add sfnettest and sfptpd to onload-sources.conf

- README.md
- onload/build/diagnostics/Dockerfile
- onload/build/diagnostics/buildconfig-nameref.yaml
- onload/build/diagnostics/buildconfig.yaml
- onload/build/diagnostics/collect_onload
- onload/build/diagnostics/kustomization.yaml
- onload/build/diagnostics/must-gather/ContainerFileNotice
- onload/build/diagnostics/must-gather/Dockerfile
- onload/build/diagnostics/must-gather/gather_onload
- onload/imagestream/imagestream.yaml
Add a new diagnostics image for the automated log collection in the OpenShift clusters with `oc adm must-gather`. The collection script is also runnable as a standalone script.
Additionally, add a new script in the onload-diagnostics image with the selected Onload log collection commands.
Reviewed-by: Peter Colledge <peter.colledge@amd.com>
---
Notes:
1. The sfreport tool is not included in the latest incarnation of this PR. We should implement SWUTILS-902 first and then pull the script from a public git repo.
2. An alternative collection method https://artifacthub.io/packages/krew/krew-index/support-bundle was considered, but it is lacking features to dynamically generate Onload logs across multiple nodes. For instance, the `runPod` or `exec` …
> ON-15040: Add onload-must-gather image for log collection

- config/rbac/role.yaml
- controllers/onload_controller.go
- controllers/onload_controller_test.go
- go.mod
- go.sum
A draft until these work items are done:
---
The operator reconciliation spawns the control plane daemon set that registers itself with the kernel module set shortly afterwards:
```console
$ oc apply -k config/samples
$ dmesg
[  +0.000023] [onload] Copyright (c) 2002-2023 Advanced Micro Devices, Inc.
[  +0.003796] [onload] oo_nic_add: ifindex=3046 oo_index=0
[Aug21 09:03] onload_cp_server[2418478]: Onload Control Plane server   started: id 0, pid 2418478
[  +0.003175] onload_cp_server[2418478]: Accelerating sf0: RX 1 TX 1
```
Testing:
```console
$ make test
KUBEBUILDER_ASSETS="/home/iteterev/lab/kubernetes-onload/bin/k8s/1.26.0-linux-amd64" go test ./... -coverprofile cover.out
?       github.com/Xilinx-CNS/kubernetes-onload [no test files]
? …
```
> ON-15121: Create control plane daemon set

- Makefile
- cmd/worker/main.go
- config/samples/onload_v1alpha1_onload.yaml
- controllers/onload_controller.go
- controllers/onload_controller_test.go
- controllers/suite_test.go
- deviceplugin.Dockerfile
- pkg/client_helper/client_helper.go
- pkg/client_helper/client_helper_test.go
- pkg/client_helper/suite_test.go
- pkg/control_plane/control_plane.go
- pkg/control_plane/control_plane_test.go
- pkg/control_plane/kernel_parameters.go
- pkg/control_plane/suite_test.go
Add the new "onload-worker" container to the existing device plugin DaemonSet.
The new container provides the Onload control plane binary to the Onload kernel instead of the dedicated control plane DaemonSet, which the next patch will remove. Additionally, it manages (`chcon` and `rm`) the Onload files in the host. Hence its name is "onload-worker".
Unlike the control plane DaemonSet, the new container uses the Golang API to get the container ID instead of the cgroup workaround.
The new GetContainerID() function resides in the "pkg" directory and is suitable for reuse.
---
It is a draft until I finish with:
---
Testing notes:
The new container does what it needs to do:
```console
$ oc logs -c onload-worker onload-sample-onload-device-plugin-ds-ltmrh
I0905 10:31:22.374698 2272581 …
```
> ON-14911: Add onload-worker container to device plugin DaemonSet

- config/manifests/bases/onload-operator.clusterserviceversion.yaml
- controllers/onload_controller_test.go
Discovered missing during pre-release checking.
> SCL-1975: Add missing license headers

- .github/workflows/unit-test.yml
https://github.com/krishd-amd/kubernetes-onload/actions/runs/6261028520
https://github.com/krishd-amd/kubernetes-onload/actions/runs/6261028520/job/17000252527
A simple action to just run the golang unit tests. In the absence of a jenkins instance, this seems rather simple and easy to get it repeatedly running on commit.
> ON-14979: Added a simple Github action to run unit tests

- ContainerFileNotice
- bundle/metadata/dependencies.yaml
- controllers/suite_test.go
Issue noticed with addition of github action for unit tests.
github action on push passed
> Cleanup: Bump kmm version to 1.1.0 in missed files

- controllers/onload_controller.go
- controllers/onload_controller_test.go
- pkg/control_plane/control_plane.go
- pkg/control_plane/control_plane_test.go
Ran `golangci-lint run ./...`, `staticcheck ./...` and `make test`
Only issue raised was by `golangci-lint` which was confiused about new definitions added in 1.21 (`min` and `max` undefined in standard library `slices` package) 
Also did a manual test to verify that the changes to `removeStaleLabels` didn't affect anything
> Cleanup: Fix various issues raised by linting

- ContainerFileNotice
- Dockerfile
- Makefile
- deviceplugin.Dockerfile
This PR addresses the `HasLicense` and `RunAsNonRoot` failures for the Device Plugin image and `HasLicense`, `HasRequiredLabel`, `BasedOnUbi` failures and the `HasNoProhibitedPackages` error for the controller manager image.
Also, it contains a tiny ContainerFileNotice fix since it's a "cleanup" PR.
Testing:
- Tested accelerated net IO in the cluster with `sfnt-pingpong`.
- Tested with the `docker://quay.io/opdev/preflight:1.7.0` utility.
Also captured some hands-on notes in Confluence: https://confluence.xilinx.com/display/~iteterev/gh+act+-+Jump+start+Guide.
> ON-14865: Resolve preflight failures and errors

- config/samples/onload-module/Dockerfile
- config/samples/onload-module/dtk-only.Dockerfile
Fix Onload Dockerfile so that depmod could compute the dependencies on the built kernel modules and modprobe could load them at runtime.
Thanks: Yevgeny Shnaidman and Quentin Barrand
---
The SFC module gets loaded if built with the MTD and VDPA support:
```
$ oc get pod; oc get module
NAME                                          READY   STATUS    RESTARTS            AGE
onload-sample-onload-device-plugin-ds-8wt4j   2/2     Running   3 (<invalid> ago)   2m58s
onload-sample-onload-device-plugin-ds-k8fvp   2/2     Running   3 (5s ago)          2m58s
onload-sample-onload-module-s7wf9-cmbx7       1/1     Running   0                   2m59s
onload-sample-onload-module-s7wf9-gbrpn       1/1     Running   0                   2m58s
onload-sample-sfc-module-nsz44-4m2ht          1/1     Running   0 …
```
> ON-15417: Fix Onload and SFC Dockerfile to load their deps at runtime

- controllers/onload_controller.go
Krish found that if a user applied a new sfc MachineConfig without first deleting the onload CR then when the node rebooted the device plugin pods were unable to restart. I believe that the issue was caused by a call to `mkdir` in the initContainer failing because the directory already existed.
I haven't re-tested the exact same scenario (applying a MachineConfig), but on a virtualised cluster I rebooted one of the worker nodes and waited for it to get back in a good state. Once the node was back online the pods were created without issue.
> Cleanup: Add -p option to mkdir in device plugin init container

- controllers/onload_controller.go
`chcon` fails in systems with disabled SELinux:
```
FailedPostStartHook  30m (x3 over 30m)  kubelet            Exec lifecycle hook ([/bin/sh -c set -e;
cp -TRv /opt/onload /host/onload;
chcon --verbose --type container_file_t --recursive /host/onload/;
]) for Container "onload-device-plugin" in Pod "dev-onload-device-plugin-ds-jxgdk_onload-runtime(b1c1ac52-6deb-4de7-b85b-d9aa0f558b23)" failed - error: command '/bin/sh -c set -e;
cp -TRv /opt/onload /host/onload;
chcon --verbose --type container_file_t --recursive /host/onload/;
' exited with 1: chcon: can't apply partial context to unlabeled file 'openonload'
chcon: can't apply partial context to unlabeled file 'onload.modules'
chcon: can't apply partial context to unlabeled file 'modules'
chcon: can't apply partial context to unlabeled …
```
> cleanup: Allow chcon failures when labelling Onload files

- config/samples/onload/onload-module/ubuntu/ContainerFileNotice
- scripts/machineconfig/ContainerFileNotice
There are two new Dockefiles: one to generate SFC MachineConfig, and another is an Onload kernel module builder for the Ubuntu kernels. This patch adds the corresponding ContainerFileNotice even though the latter image is a template.
---
Re on Dockerfiles:
- I chose the specific version of Butane (v0.19.0), which must be the latest `release` tag.
- Ubuntu is borderline, as we don't build these images, but added for completeness.
> cleanup: Add ContainerFileNotices for Ubuntu & MachineConfig

- DEVELOPING.md
- Makefile
- api/v1alpha1/onload_types.go
- config/crd/bases/onload.amd.com_onloads.yaml
- config/manager/kustomization.yaml
- config/manager/kustomizeconfig.yaml
- config/manager/manager.yaml
- config/samples/default-clusterlocal/kustomization.yaml
- config/samples/onload/base/configurations.yaml
- config/samples/onload/base/onload_v1alpha1_onload.yaml
- config/samples/onload/overlays/in-cluster-build-ocp-clusterlocal/kustomization.yaml
- config/samples/onload/overlays/in-cluster-build-ocp/kustomization.yaml
- controllers/onload_controller.go
- controllers/onload_controller_test.go
- controllers/suite_test.go
- main.go
Previously the device plugin image would be set per Onload CR, this could potentially lead to confusion since (we expect) most users won't need to change the device plugin image nor have fine-grained control of the image. Additionally, since we have built the controller with certain assumptions of the device plugin image it should lower the chances that a user sets this to an incompatible value.
I have left a field for the ImagePullPolicy in the `DevicePluginSpec` struct, though I'm wondering how necessary that is.
Tested in virtualised cluster, when an onload CR is created it creates the device plugin correctly.
Since the value of the device plugin image is set at operator deploy time, I have found that the best way to deploy the operator is with the command
```
make deploy IMG=... …
```
> Set Device Plugin Image at controller level

- README.md
- controllers/onload_controller.go
- controllers/onload_controller_test.go
- Reduced both module suffixes to 7 characters: `-module` for `onload` and `-sfcmod` for `sfc`
- The reconciler will return an error in the bad case rather than creating the module
- Added a unit test
- Added an "important" line to the readme
> ON-15481: Shorten name suffix and add length check
